"""rename department

Revision ID: e454b8e3fd9c
Revises: ae85f5eadb17
Create Date: 2026-01-12 12:47:37.272728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e454b8e3fd9c'
down_revision = 'ae85f5eadb17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
